# Generated by Django 5.2.1 on 2025-07-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobAggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregation_date', models.DateField()),
                ('source', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=10)),
                ('query_term', models.CharField(max_length=100)),
                ('total_offers', models.IntegerField()),
                ('offers_with_salary', models.IntegerField()),
                ('avg_salary_min', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('avg_salary_max', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('avg_salary_avg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('top_company', models.CharField(max_length=255, null=True)),
                ('top_company_count', models.IntegerField(null=True)),
                ('top_location', models.CharField(max_length=255, null=True)),
                ('top_location_count', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'job_aggregations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('contract_type', models.CharField(max_length=255)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'job_offers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobOfferClean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=10)),
                ('query_term', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('salary_min', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('salary_avg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField()),
                ('created', models.DateTimeField()),
                ('scraped_at', models.DateTimeField(null=True)),
                ('age_offre_jours', models.IntegerField()),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'job_offers_clean',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobteaserOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('contract_type', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('contract_category', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'jobteaser_offers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OffersPerContract',
            fields=[
                ('contract_type', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('offer_count', models.IntegerField()),
            ],
            options={
                'db_table': 'offers_per_contract',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OffersPerContractCategory',
            fields=[
                ('contract_category', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('offers_count', models.IntegerField()),
            ],
            options={
                'db_table': 'offers_per_contract_cat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OffersPerCountryJobteaser',
            fields=[
                ('country', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('offers_count', models.IntegerField()),
            ],
            options={
                'db_table': 'offers_country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OffersPerCountryMeteojob',
            fields=[
                ('country', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('offers_count', models.IntegerField()),
            ],
            options={
                'db_table': 'offers_per_country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalaryMeanPerContract',
            fields=[
                ('contract_type', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('avg_salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'salary_mean_per_contract',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalaryMeanPerCountry',
            fields=[
                ('country', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('avg_salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'salary_mean_per_country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalaryMeanTopCompanies',
            fields=[
                ('company', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('avg_salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'salary_mean_top_companies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TopCitiesPerCountry',
            fields=[
                ('country', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=255)),
                ('offers_count', models.IntegerField()),
            ],
            options={
                'db_table': 'top_cities_per_country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TopCompanies',
            fields=[
                ('company', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('offer_count', models.IntegerField()),
            ],
            options={
                'db_table': 'top_companies',
                'managed': False,
            },
        ),
    ]
